version: '2'
services:
  db:
    image: postgres
  restapi:
    build: restapi
    command: python manage.py run
    volumes:
      - ./restapi:/code
    ports:
      - "5000:5000"
    links:
      - db
      - user
  user:
    build: user
    command: python manage.py run
    volumes:
      - ./user:/code
    ports:
      - "5001:80"
    links:
      - db
  favour:
    build: favour
    command: python manage.py run
    volumes:
      - ./favour:/code
    ports:
      - "5002:80"
    links:
      - db
